# Generated by Django 3.2.25 on 2024-11-22 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20241122_2031'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persons', models.JSONField(default=list)),
                ('phone_numbers', models.JSONField(default=list)),
                ('emails', models.JSONField(default=list)),
                ('skills', models.JSONField(default=list)),
                ('designations', models.JSONField(default=list)),
                ('organizations', models.JSONField(default=list)),
                ('dates', models.JSONField(default=list)),
                ('educations', models.JSONField(default=list)),
                ('institutes', models.JSONField(default=list)),
                ('date_of_birth', models.JSONField(default=list)),
            ],
        ),
        migrations.RemoveField(
            model_name='skill',
            name='person',
        ),
        migrations.RemoveField(
            model_name='workexperience',
            name='person',
        ),
        migrations.DeleteModel(
            name='Education',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
        migrations.DeleteModel(
            name='WorkExperience',
        ),
    ]
